# .github/workflows/docker.yml
name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      - name: Login to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ secrets.DOCKER_REGISTRY }}
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/personal-blog:${{ github.sha }}
          # Diabled due to cloudflares upload limit.
          # Seems like the buildcache is generating at least one large layer.
          # cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/personal-blog:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/personal-blog:buildcache,mode=max
